services:
#    tag.example:
#        class: Russia\TagBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  tag.form.type.tags:
    class: Russia\TagBundle\Form\Type\TagsType
    arguments: ['@doctrine.orm.entity_manager']
    tags:
      - { name: form.type }